pow_dense
qutip/qutip-cupy pull request #29
Opened 2021-07-29 00:20 UTC by MrRobot2211

This implements pow and creates a class that should be inside QuTiP proper to do the testing.

We can afterwards add the test class to qutip and inherit here in future PRs.

This in pursuit of having the most functionality available on the "first" release.

This is ready to merge after extra_functions

2021-08-03 11:16 UTC, hodgestar requested changes

2021-08-03 11:16 UTC, hodgestar commented on src/qutip_cupy/dense_functions.py
> +        raise TypeError("matrix power only works with square matrices")
```suggestion
        raise ValueError("matrix power only works with square matrices")
```
The type is correct, but the shape is not.

2021-08-03 11:16 UTC, hodgestar commented on tests/test_mathematics.py
> +    ]
We should add tests for the exception case too -- i.e. `bad_shapes = [...]` and the suitable error test method.

2021-08-04 18:22 UTC, AGaliciaMartinez commented
The class `PowTest` is now merged in dev.major. :)

2021-08-05 14:13 UTC, MrRobot2211 commented
@hodgestar I think this is ready then, I'll inherit from the newly minted QuTiP tests later on.

2021-08-06 15:02 UTC, hodgestar approved these changes

2021-08-06 15:06 UTC, hodgestar commented on tests/test_mathematics.py
> +    ]
```suggestion
    ]

```

2021-08-06 15:06 UTC, hodgestar commented on src/qutip_cupy/dense_functions.py
> +        raise ValueError("state must be a ket or a bra.")
```suggestion
        raise ValueError("state must be a ket or a bra.")
```

2021-08-06 15:09 UTC, hodgestar approved these changes
I had to resolve some merge conflicts. Approved again. :)

2021-08-06 15:10 UTC, hodgestar commented
@MrRobot2211 Approved! Happy for you to merge once the test run passes.

2021-08-06 15:25 UTC, hodgestar commented on src/qutip_cupy/dense_functions.py
> +
```suggestion

```

2021-08-06 15:33 UTC, hodgestar commented
@MrRobot2211 Could you fix up the silly pep 8 errors resulting from my merging with GitHub's merge interface? Apologies for leaving you with the mess but I am stepping away from my computer now and don't have the branch checked out to do the clean up quickly.

2021-08-06 18:57 UTC, merged