dense_norms
qutip/qutip-cupy pull request #30
Opened 2021-07-29 04:34 UTC by MrRobot2211

This implements the noms in data.norms

Tests are not present in QuTiP so they are created here for the sake of speeding things up. But we really should have the tests on dev.major and the inherit them here.

2021-08-03 11:11 UTC, hodgestar commented
@MrRobot2211 Could you merge the main branch into this one now that extra functions has been merged? At the moment the diff is large and contains mostly stuff that is already reviewed and merged into main.

2021-08-06 15:23 UTC, hodgestar requested changes
Left some small suggestions, but otherwise looks good.

2021-08-06 15:23 UTC, hodgestar commented on src/qutip_cupy/dense_functions.py
> +
```suggestion
```

2021-08-06 15:23 UTC, hodgestar commented on src/qutip_cupy/__init__.py
> +data.norm.one.add_specialisations([(CuPyDense, cdf.one_cupydense)])
```suggestion
data.norm.l2.add_specialisations([(CuPyDense, cdf.l2_cupydense)])
data.norm.frobenius.add_specialisations([(CuPyDense, cdf.frobenius_cupydense)])
data.norm.max.add_specialisations([(CuPyDense, cdf.max_cupydense)])
data.norm.one.add_specialisations([(CuPyDense, cdf.one_cupydense)])

```
Putting these into a separate paragraph and removing the comment about the dispatching being weird. This is not weird -- namespacing is a core Python feature!

2021-08-06 15:23 UTC, hodgestar commented on tests/test_mathematics.py
> +    # Trace actually does have bad shape, so we put that in too.
```suggestion
    # l2 norm actually does have bad shape, so we put that in too.
```

2021-08-06 20:54 UTC, MrRobot2211 commented
Ready to merge

2021-08-07 15:32 UTC, hodgestar approved these changes
Approved!

2021-08-07 15:32 UTC, merged