dense_project
qutip/qutip-cupy pull request #31
Opened 2021-08-03 06:33 UTC by MrRobot2211

This implements the projection operator function and test with CuPyDense arrays

2021-08-03 11:03 UTC, hodgestar requested changes

2021-08-03 11:03 UTC, hodgestar commented on src/qutip_cupy/dense_functions.py
> +        raise TypeError("state must be a ket or a bra.")
```suggestion
        raise ValueError("state must be a ket or a bra.")
```
I think this is technically a `ValueError` since the type is correct.

2021-08-03 11:03 UTC, hodgestar commented on src/qutip_cupy/__init__.py
> +data.project.add_specialisations([(CuPyDense, CuPyDense, cdf.trace_cupydense)])
The fact that tests didn't pick this up suggests that we need another layer of tests. We shouldn't add them in this PR, but we do really need to check that the specialisations are hooked up correctly (i.e. probably tests at the Qobj level with CuPyDense Qobjs).

2021-08-04 18:42 UTC, MrRobot2211 commented
@hodgestar  I think this one is good to go

2021-08-06 14:57 UTC, hodgestar approved these changes

2021-08-06 14:59 UTC, merged